name: Build documentation
on:
  push:
    branches: ["main"]  # Replace 'main' with your branch name
  workflow_dispatch:     # Allow manual triggering
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Writerside docs
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: Writerside/hi    # Update if your module/instance differs
          artifact: webHelpHI2-all.zip # Update if your module/instance differs
          docker-version: 'latest'

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages       # The branch the action should deploy to.
          folder: webHelpHI2-all # The folder the action should deploy. Update if needed.
